### ISSUE TITLE
This is not an issue.

### ISSUE THREAD

**Issue by Spork-Schivago** [kakaroto/e17#2]
Kakaroto, I'm sorry for contacting you this way.  I couldn't really figure out how else to contact you.  This has nothing to do with your E17 stuff.  I wanted to know if I paid you 50$ or so, if you could add something to PSL1GHT for me.  I've downloaded the PS3Toolchain and I've updated it.  For example, it had gcc 4.7.0.  Mine has 4.8.2.  I've updated your EFL libraries to the latest as well, except for one of them which needed scandir I think.  Anyways, I'm almost down with the PS3 Libraries.  I would like it if you could possible include a gethostname() function in maybe the libnet library.  You can contact me via e-mail if you're interested.  Spork [at] stny [dot] rr [dot] com .  Thanks for all the hard work you've done over the years with all the PS3 stuff.

**Comment by kakaroto** [comment]
Sorry I'm not interested in any paid work.
Do you want gethostname() or gethostbyname() ? because gethostbyname() is already implemented in PSL1GHT (net/netdb.h) and gethostname is completely useless in your case. so you can easily fake it with a dummy :
   int gethostname(char *name, size_t len) { strncpy(name, "ps3", len); }

**Comment by Spork-Schivago** [comment]
Thank you, I wasn't sure about that.  Anyways, I managed to get around that problem.  I'm now trying to get the new version of fontconfig (2.11.0) to compile.  I've manually updated all the packages in the PS3 Toolchain and the PS3 Libraries to the latest and greatest versions.  I'm working on doing the same for your EFL libraries, however, I'm having difficulties with the fontconfig package.  I asked on Tortuga Cove if anyone wanted or could help but I didn't really get a response.  Some of the mailing lists have been helpful.  I'm not 100% sure I did the Curl stuff right though.  I have the latest version of PolarSSL installed now and Curl still uses the older version.  I had to manually change the functions.  I'm just not that good when it comes to SSL stuff.  Thanks for the info though.

On Friday, December 13, 2013 12:43 AM, kakaroto notifications@github.com wrote:

Closed #2.

**Comment by kakaroto** [comment]
I don't remember having issues with fontconfig. To update the EFL libraries to the latest would require some work since many things changed. The important part is that I think EFL now requires threads and cannot work without pthread so we'd first need to have a ps3 version of the pthreads library. Also, the latest EFL is not a single package (called 'efl') instead of a collection of many smaller packages.
Good luck with it. Let me know if you make any progress.

**Comment by Spork-Schivago** [comment]
I've made some progress.  With the help from the people from the fontconfig mailing list, i got past that issue.  I thought I was using the latest version of the EFL packages but I was wrong.  It appears they moved most of the packages that were included in your EFL libraries for the PS3 are now included in a package called Ecore.  So I'm compiling most of the packages as version 1.7.9.  I tried compiling Ecore 1.8.2 with little success.  It needed some dependencies that I couldn't get.  I installed some extra libraries and made it to the point where configure was complaining about not having EPhysics.  I tried to install EPhysics but it needed Bullet.  I tried to install Bullet but it errored out with configure: WARNING: **\* Please add powerpc64-ps3-elf to configure.ac checks!
configure: error: Unknown Architecture and I couldn't figure out how to add powerpc64-ps3-elf to the configure.ac checks.  I also want to say there was something about opengl.  I just can't remember.

I think I'll just stick with the 1.7.9 packages for now.  Also, with the 1.7.9 packages, I've made it up to Evas.  My version of the libraries use SDL2.  I think I'm going to have to include SDL1 as well as SDL2 because I tried porting the Evas code to use SDL2 and it's a bit more than what I'm capable of I believe.

**Comment by Spork-Schivago** [comment]
Okay, now I have a problem with Expedite-1.7.9.  I try compiling and I receive an error that says main.h cannot find engine_psl1ght.h.  I have checked my whole system and could not find one.   It first checks to see if evas is installed (which it is) and then it tries to include the file (in double quotes).  I replaced it with Evas_Engine_PSL1GHT.h and evas_engine.h hoping it'd fix the problem.  Then it errors out about these not being declared:

../../../src/bin/main.c:1177:19: error: 'engine_psl1ght_args' undeclared here (not in a function)
   { "psl1ght",    engine_psl1ght_args, engine_psl1ght_loop, engine_psl1ght_shutdown },
                   ^
../../../src/bin/main.c:1177:40: error: 'engine_psl1ght_loop' undeclared here (not in a function)
   { "psl1ght",    engine_psl1ght_args, engine_psl1ght_loop, engine_psl1ght_shutdown },
                                        ^
../../../src/bin/main.c:1177:61: error: 'engine_psl1ght_shutdown' undeclared here (not in a function)
   { "psl1ght",    engine_psl1ght_args, engine_psl1ght_loop, engine_psl1ght_shutdown },

Any ideas?   Was the evas_engine.h in an older version of Expedite or something?  Thanks for the help.

**Comment by Spork-Schivago** [comment]
To get around the problem, I created the file with a version I found in the old e17 stuff.   I think this file should be included in the Expedite compressed archive stored on the enlightenment servers, personally...this is the contents of that file:

#ifndef ENGINE_SOFTWARE_PSL1GHT_H
#define ENGINE_SOFTWARE_PSL1GHT_H

Eina_Bool engine_psl1ght_args(const char *engine, int width, int height);
void engine_psl1ght_loop(void);
void engine_psl1ght_shutdown(void);

#endif

**Comment by Spork-Schivago** [comment]
One last thing, and then I promise I'll leave you alone.  I'm not very good with sed and in your build_ps3elf.sh script, you have this line: 
sed -e "s/Test - PSL1GHT/$title/" -e "s/TEST00000/appid/" sfo.xml > ps3sfo.xml || return 1

When I put that line in my script file, I get an error saying: 
sed: -e expression #2, char 18: unknown option to `s'

You wouldn't know what I'm doing wrong, would you?  I originally copied and pasted it from your script but I read there might of been some weird character at the end or something so I manually typed it.  Both times, I got the same error.

**Comment by Spork-Schivago** [comment]
sorry, I accidently removed the $ from appid.  With the $, the problem is still there....

**Comment by Spork-Schivago** [comment]
I figured it out, thanks.

**Comment by Spork-Schivago** [comment]
Okay, I finished it.  My version of the toolchain uses binutils-2.32.2, gcc-4.8.2, gdb-7.6.1, newlib-2.0.0, psl1ght and the ps3libraries.

My version of the ps3libraries uses zlib-1.2.8, libpng-1.6.6, jpeg-v9, freetype-2.5.0.1, pixman-0.32.2, cairo-1.12.16, libog-1.3.1, libvorbis-1.33, libzip-0.11.1, tiff-4.0.3, libmikmod-3.3.3, libxml2-2.9.1, webp-0.3.1, flac-1.3.0, libmad-0.15.1b, SDL-psl1ght, SDL-libs, SDL2-2.0.1, SDL2-libs (which includes all the libs from SDL-libs but the SDL2 versions), polarssl-1.3.2, libcurl-7.33.0, faad2-2.7, libtheora-1.1.1, libintl-lite-0.5, NoRSX-0.3.1, libjson-0.11

My version of the EFL libraries uses your version of escape, eina-1.7.9, eet-1.7.9, expat-2.1.0, fontconfig-2.11.0, evas-1.7.9, expedite-1.7.9, c-ares-1.10.0, ecore-1.7.9, embryo-1.7.9, lua-5.2.3, edje-1.7.9, chipmunk-6.2.1, your version of eskis and elementary-1.7.9.

I found out that I could download the EFL 1.8.1 stuff from github but at that point in time, I was working on the last one, elementary, and didn't want to start over.

I tried running the sample program from NoRSX and it ran extremely slow and I couldn't exit.  I don't know if it's a problem with something I did or what.   Also, I'm not 100% sure I patched libcurl right to use the newer version of polarssl (it only supported the last previous versions (anything before 1.3)  I'd love to have someone a bit more experienced check out my patches and everything before I make fool out of myself and post it on the net.  Let me know if you're interested...and thanks for all the hard work you've  down over the years with the scene and everything.

**Comment by Spork-Schivago** [comment]
Well, if you want to check it out, just download it: https://github.com/Spork-Schivago/toolchain

**Comment by kakaroto** [comment]
Nicely done..  I'm reinstalling my PC now so i'll be trying your toolchain on the new laptop, i'll let you know how it works.
so far however, i can't get binutils to compile because of this error :
http://trac.cross-lfs.org/ticket/926

**Comment by Spork-Schivago** [comment]
Sorry it took so long to get back to you.  I've been diagnosed with something called Central Pain Syndrome.  My Central Nervous System is damaged and I've been in a lot of pain.  The doctors said they can't make the pain go away but they'll try to make me as comfortable as possible.  I haven't been able to work on the toolchain for a bit now.   You can view the commits I've made on the repository.  There's something wrong with the EFL stuff.  Any homebrew, including Eskiss and Escape crash back to the XMB.   I started debugging it over the network by modifying the libraries on my local system to use some tcp_printf functions I borrowed from RSXGL.  One of the changes I made to Eskiss was in main.c, in the main function, I added a char  name[] = "eskiss"; and I changed _drawin_log_domain = eina_log_domain_register("eskiss", EINA_COLOR_CYAN);  to _drawin_log_domain = eina_log_domain_register(name, EINA_COLOR_CYAN);   On my system, this seemed to make it go further.   Either that or I didn't have enough tcp_printf's in the other libraries.

**Comment by Spork-Schivago** [comment]
I will try to fix the binutils stuff in the next couple of days.   They put me on some new meds that might help a bit.

**Comment by Spork-Schivago** [comment]
From what I've read, the problem should be fixed in 2.24.  I've updated the toolchain to use the new binutils-2.24.  Also, I've updated a few other things.  Best to clone the repo again and try it again if you don't mind.
