### ISSUE TITLE
c-ares doesn't work...

### ISSUE THREAD

**Issue by Spork-Schivago** [kakaroto/e17#3]
I noticed when building the EFL libraries for the PS3, you include the c-ares library and it gets built.  However, I believe in it's current state it isn't usable.   It seems to look for DNS servers in /etc/resolv.conf and it examines /etc/hosts as well.   As I'm sure you know, these files don't exist on the PS3.   Just wanted to know if you had any plans on porting it or any suggestions on what files in c-ares might need to be modified in order for it to work on the PS3.   Thanks for all the effort you put into this!

**Comment by kakaroto** [comment]
Hi,
Sorry but I don't have any plans or anything related to PS3, I just don't have the time or motivation anymore to play with that stuff. It was fun while it lasted but I've moved on : )
Thanks for reporting the issue. If you get it fixed, I'll merge it.

**Comment by Spork-Schivago** [comment]
Okay, thanks for letting me know.  You've done some amazing things with the PS3.   Sorry to see you not involved anymore with it.   I understand though.   I hope what ever you're working on now is equally as enjoyable for you.

**Comment by kakaroto** [comment]
I think you clicked "Close and comment" instead of just "comment" so I reopened the issue. Only close it if it's fixed : )
And thanks for keeping this stuff alive. I'm having fun in what I do now, but I'm mostly busy with work.

**Comment by Spork-Schivago** [comment]
I did close it on accident.  It's been a busy past couple of weeks.  Sorry for that and thank you.

**Comment by kakaroto** [comment]
Closing because this project is unmaintained and I never plan on maintaining it again.

**Comment by Spork-Schivago** [comment]
I have moved on too now Kakaroto and have a beautiful daughter and wife now.   I no longer have the time nor motivation to work on this either, the time has passed for me as well sir!   Thank you for the time and effort you and everyone else put into the original projects.   It has provided me with truly amazing memories sir.

**Comment by kakaroto** [comment]
Congratulations on the wife and daughter :) Enjoy your life, and I wish you more happy memories for you and your family's future :)
Take care.
