### ISSUE TITLE
currently unimplemented ecore_x_image_get without shm

### ISSUE THREAD

**Issue by seisdr** [kakaroto/e17#4]
What is the case of this error

**Comment by kakaroto** [comment]
No idea, i haven't updated or even looked at the efl since 2013.... I also don't plan to, so I'm closing this issue. Feel free to fork and maintain it on your own repo.

**Comment by seisdr** [comment]
That was fast

**Comment by kakaroto** [comment]
was checking my emails at the same time the notification came in :p
